### ISSUE TITLE
Incorrect PubMed ID in assertions 695 and 755

### ISSUE THREAD

**Issue by cgrisdale** [vanallenlab/moalmanac-browser#45]
Hello, there appears to be a digit missing from the pmid: returned via API for assertions 695 (https://moalmanac.org/api/assertions/695) and 755 (https://moalmanac.org/api/assertions/755).

`"pmid": 7486065,`

The correct pmid is 17486065: https://pubmed.ncbi.nlm.nih.gov/17486065/

**Comment by brendanreardon** [comment]
Oh gosh. Thank you for finding this and reaching out! We just edited the database for this change to be resolved in [our October release](https://github.com/vanallenlab/moalmanac-db/pull/31), scheduled for next Thursday.

**Comment by cgrisdale** [comment]
That's great. Thanks for taking care of that so quickly.
